# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4397d284f9efc5ddb2aad14f6b351983b2f1f3379f462bdae74b10c922b1c574b9af29cbab19173b1c428096c1bc2360ae671077da8ade2067dbfdeb19fcab0d

test:
  secret_key_base: c35a1445fbc39cd3aafa54e6ba0465aec2b10b6bd41c2f75cbf0dbfabe5afe25094a924b187b7c23a562ab4e5d7ff9be8332566ebde0780a697272dc57d742f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
